# Generated by Django 3.2.5 on 2021-11-22 13:18

from django.db import migrations

def create_first_movie(apps, schema_editor):
    
    Movie = apps.get_model('movies', 'Movie')
    Movie.objects.create(
        title='Genesis',
        genre='comedy',
        plot='Some dev comes up with an imaginary movie'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_created_by'),
    ]

    operations = [
        migrations.RunPython(create_first_movie),
    ]
